### ISSUE TITLE
CICFLOWMETER GENERATING empty flow

### ISSUE THREAD

**Issue by Jiarubab** [ahlashkari/CICFlowMeter#140]
I want to generate flow from CICFLOWMETER by its showing all packets ignored. Here is a snapshot of my problem. 

![Capture](https://user-images.githubusercontent.com/100867664/165626583-eec904cb-be35-4728-be9b-efbdb0000997.PNG)

**Comment by hasnaamohi** [comment]
Did you solve this proplem ?

**Comment by Jiarubab** [comment]
No Sir.
________________________________

**Comment by souravs17031999** [comment]
@hasnaamohi @Jiarubab was this solved, I am facing same.

**Comment by hasnaamohi** [comment]
No

في الجمعة، ٢٤ فبراير ٢٠٢٣, ٦:٤٢ م Sourav Kumar ***@***.***>
كتب:

**Comment by hessammohammadian** [comment]
The problem is not the CICFlowmeter. It's probably from your pcap file. If the pcap files don't have an actual ethernet layer the CICFlowmeter can't detect any flows. As you can see in your output all packets are ignored. You need to add the ethernet layer to all pcap files and then it will work.
tcprewrite --dlt=enet --infile="" --outfile=""
