### ISSUE TITLE
IPv6

### ISSUE THREAD

**Issue by matthbr** [ahlashkari/CICFlowMeter#49]
I have a dataset containing both IPv4 and IPv6 flows and as far as I can see the CICFlowMeter includes code to handle IPv6 packets but it is disabled in the class function
`public class CICFlowMeter {

	public static final Logger logger = LoggerFactory.getLogger(CICFlowMeter.class);
	public static void main(String[] args) {
		
		PacketReader    packetReader;
		BasicPacketInfo basicPacket = null;
		FlowGenerator   flowGen; //15000 useconds = 15ms
		
		boolean readIP6 = false;
		boolean readIP4 = true;`

so I wanted to ask if there is a reason for that. Is something not correctly working with IPv6 or can it simply be activated by setting readIP6 to true?

**Comment by ahlashkari** [comment]
Yes, you just need to set readIP6 to True.

**Comment by Cyan95** [comment]
> Yes, you just need to set readIP6 to True.

I've encountered the same problem.

I tried the advice, but it didn't seem to work.

And only 1/3 packets can find the belonging flow.

The pcap file and the flow csv file generated are attached in the zip.

In addition, the pcap file is from the ISCX2016 dataset.

[email1a.zip](https://github.com/ahlashkari/CICFlowMeter/files/5708037/email1a.zip)

**Comment by lexiea** [comment]
I had the same problem. I fixed it by setting `readIP6 = true` not only once but in two different files: in `CICFlowMeter.java` in `public static void main(String[] args) {...}`, and in `ReadPcapFileWorker.java` in `public class ReadPcapFileWorker extends SwingWorker<List<String>,String>{...}`.

The variable is set a third time in `PacketReader.java{...}` in `public PacketReader(String filename) {...}`, however, it seems there you could leave it set to `false` because this function is never called (instead this function is used: `public PacketReader(String filename, boolean readip4, boolean readip6) {...}`). 

Then I found one last place that could create problems: in the file `TrafficFlowWorker.java` in `PcapPacketHandler<String> jpacketHandler = (packet, user) -> {...}` `flowGen.addPacket(PacketReader.getBasicPacketInfo(permanent, true, false));` is called where the last boolean argument is `readIP6` . I didn't dig quite deep enough to see if this could make a difference, it did not make a difference for me.

I hope this might help someone else :)
